<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<KingoDomainLibrary>true</KingoDomainLibrary>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kingo\Kingo.csproj" />
		<ProjectReference Include="..\Kingo.Facts\Kingo.Facts.csproj" />
		<ProjectReference Include="..\Kingo.Theories\Kingo.Theories.csproj" />
	</ItemGroup>

</Project>
